services:
  youtube_web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --no-input &&
             python manage.py runserver 0.0.0.0:8008"
    volumes:
      - ./:/app
      - django_static:/app/static
      - download_files:/app/downloads
      - ./backups:/app/backups
    env_file:
      - .env
    ports:
      - "8008:8008"
    depends_on:
      - youtube_db

  youtube_db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  youtube_bot:
    build: .
    command: python manage.py runbot
    volumes:
      - .:/app
      - download_files:/app/downloads
    env_file:
      - .env
    depends_on:
      - youtube_db


volumes:
  postgres_data:
  django_static:
  download_files:
