services:
  youtube_web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --no-input &&
             python manage.py runserver 0.0.0.0:8008"
    volumes:
      - ./:/app
      - django_static:/app/staticfiles
      - download_files:/app/downloads
      - ./backups:/app/backups
    env_file:
      - .env
    ports:
      - "8008:8008"
    depends_on:
      - youtube_db

  youtube_db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  youtube_bot:
    build: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: python manage.py runbot
    volumes:
      - .:/app
      - download_files:/app/downloads
      - ./youtube.com_cookies.txt:/app/youtube.com_cookies.txt:rw
      - ./instagram.com_cookies.txt:/app/instagram.com_cookies.txt:rw
      - ./tiktok.com_cookies.txt:/app/tiktok.com_cookies.txt:rw
    env_file:
      - .env
    depends_on:
      - youtube_db

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - django_static:/app/static
    ports:
      - "80:80"
    depends_on:
      - youtube_web

volumes:
  postgres_data:
  django_static:
  download_files:
