# Generated by Django 5.2 on 2025-04-12 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('new_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('total_downloads', models.IntegerField(default=0)),
                ('video_downloads', models.IntegerField(default=0)),
                ('audio_downloads', models.IntegerField(default=0)),
                ('successful_downloads', models.IntegerField(default=0)),
                ('failed_downloads', models.IntegerField(default=0)),
                ('total_download_size', models.BigIntegerField(default=0)),
                ('avg_processing_time', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Daily Stat',
                'verbose_name_plural': 'Daily Stats',
                'indexes': [models.Index(fields=['date'], name='bot_dailyst_date_22c369_idx')],
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('language_code', models.CharField(blank=True, max_length=10, null=True)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Telegram User',
                'verbose_name_plural': 'Telegram Users',
                'indexes': [models.Index(fields=['telegram_id'], name='bot_telegra_telegra_3bed65_idx'), models.Index(fields=['join_date'], name='bot_telegra_join_da_63f929_idx'), models.Index(fields=['last_active'], name='bot_telegra_last_ac_c3ed16_idx')],
            },
        ),
        migrations.CreateModel(
            name='DownloadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField(max_length=255)),
                ('video_title', models.CharField(blank=True, max_length=255, null=True)),
                ('download_type', models.CharField(choices=[('VIDEO', 'Video'), ('AUDIO', 'Audio')], max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='bot.telegramuser')),
            ],
            options={
                'verbose_name': 'Download Activity',
                'verbose_name_plural': 'Download Activities',
                'indexes': [models.Index(fields=['started_at'], name='bot_downloa_started_4ff642_idx'), models.Index(fields=['download_type'], name='bot_downloa_downloa_cd8634_idx'), models.Index(fields=['success'], name='bot_downloa_success_5b5887_idx')],
            },
        ),
    ]
